# Generated by Django 4.2.3 on 2024-02-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_photos_delete_taskphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photos',
        ),
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='task_photos/'),
        ),
    ]
